# Generated by Django 2.2.12 on 2020-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_stockermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDispatcherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
